name: Generate kb

on:
  issue_comment:
    types: [created]

jobs:
  sync:
    name: Generate kb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/gnebbia/kb

      - name: Generate new kb
        if: contains(github.event.issue.labels.*.name, 'kb') && github.event.comment.user.login == 'yihong0618'
        run: |
          ./kb_gen.sh '${{github.event.comment.body}}' '${{github.event.issue.title}}'

      - name: Push new kb
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.G_T }}
          commit-message: "push new kb"
          files: kb_data/
          rebase: 'true'
          name: yihong0618 
          email: zouzou0208@gmail.com
